### ISSUE TITLE
cmb.each is not a function

### ISSUE THREAD

**Issue by andreis** [dankogai/js-combinatorics#27]
Doesn't seem to work in node 5.10.1. I ran the module's tests with mocha and that worked, so not sure what the issue is.

```lang=text
$ node --version
v5.10.1
$ node
> var Combinatorics = require('js-combinatorics');
undefined
> var cmb, a;
undefined
> cmb = Combinatorics.power(['a','b','c']);
[Number: 8]
> cmb.each(function(a){ console.log(a) });
TypeError: cmb.each is not a function
    at repl:1:5
    at REPLServer.defaultEval (repl.js:269:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:439:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
```

**Comment by addobandre** [comment]
The problem is a typo. The correct function is `cmb.forEach` :)

**Comment by andreis** [comment]
https://github.com/dankogai/js-combinatorics/commit/77289f5c7f7a217dfe2ef90e97714232acbbe81e#diff-04c6e90faac2675aa89e2176d2eec7d8R24
